{
  "formatVersion": "1.1",
  "component": {
    "group": "com.practicalunittesting.chp03.money",
    "module": "money-lib",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "vzwbxpyu3ndypi6yvbjdhz623a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "money-lib-1.0.jar",
          "url": "money-lib-1.0.jar",
          "size": 2069,
          "sha512": "2450fddf454ff5e8ce61cc6cdab617933e37f2b005c764e5b41246feec31e4c30e314713f49557b0b906917ed3aab7d933b58fd5563a5d9eaff76fc3a64b3102",
          "sha256": "d079eac12140b73468ccc6249d3a6bd9bf20a1897396486137ad4d6091fa6b57",
          "sha1": "ac132eb2f4a66723b7f5af20767db374c07c7a44",
          "md5": "e3aec0075585c2d6278744a23663dfbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 15,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        }
      ],
      "files": [
        {
          "name": "money-lib-1.0.jar",
          "url": "money-lib-1.0.jar",
          "size": 2069,
          "sha512": "2450fddf454ff5e8ce61cc6cdab617933e37f2b005c764e5b41246feec31e4c30e314713f49557b0b906917ed3aab7d933b58fd5563a5d9eaff76fc3a64b3102",
          "sha256": "d079eac12140b73468ccc6249d3a6bd9bf20a1897396486137ad4d6091fa6b57",
          "sha1": "ac132eb2f4a66723b7f5af20767db374c07c7a44",
          "md5": "e3aec0075585c2d6278744a23663dfbd"
        }
      ]
    }
  ]
}
